//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.10 at 06:18:54 PM UTC 
//


package xml.a1.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Lice" type="{a1ns}TFizicko_lice" minOccurs="0"/&gt;
 *         &lt;element name="Pseudonim_autora" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Godina_smrti" type="{http://www.w3.org/2001/XMLSchema}gYear" minOccurs="0"/&gt;
 *         &lt;element name="Autor_anoniman" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "lice",
    "pseudonimAutora",
    "godinaSmrti",
    "autorAnoniman"
})
@XmlRootElement(name = "Autor")
public class Autor {

    @XmlElement(name = "Lice")
    protected TFizickoLice lice;
    @XmlElement(name = "Pseudonim_autora")
    protected String pseudonimAutora;
    @XmlElement(name = "Godina_smrti")
    @XmlSchemaType(name = "gYear")
    protected XMLGregorianCalendar godinaSmrti;
    @XmlElement(name = "Autor_anoniman", defaultValue = "false")
    protected boolean autorAnoniman;

    /**
     * Gets the value of the lice property.
     * 
     * @return
     *     possible object is
     *     {@link TFizickoLice }
     *     
     */
    public TFizickoLice getLice() {
        return lice;
    }

    /**
     * Sets the value of the lice property.
     * 
     * @param value
     *     allowed object is
     *     {@link TFizickoLice }
     *     
     */
    public void setLice(TFizickoLice value) {
        this.lice = value;
    }

    /**
     * Gets the value of the pseudonimAutora property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPseudonimAutora() {
        return pseudonimAutora;
    }

    /**
     * Sets the value of the pseudonimAutora property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPseudonimAutora(String value) {
        this.pseudonimAutora = value;
    }

    /**
     * Gets the value of the godinaSmrti property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getGodinaSmrti() {
        return godinaSmrti;
    }

    /**
     * Sets the value of the godinaSmrti property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setGodinaSmrti(XMLGregorianCalendar value) {
        this.godinaSmrti = value;
    }

    /**
     * Gets the value of the autorAnoniman property.
     * 
     */
    public boolean isAutorAnoniman() {
        return autorAnoniman;
    }

    /**
     * Sets the value of the autorAnoniman property.
     * 
     */
    public void setAutorAnoniman(boolean value) {
        this.autorAnoniman = value;
    }

}
