//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.10 at 06:18:54 PM UTC 
//


package xml.a1.model;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Naslov_dela" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Alternativni_naslov" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element ref="{a1ns}Delo_prerade" minOccurs="0"/&gt;
 *         &lt;element name="Vrsta_autorskog_dela" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Forma_zapisa" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Delo_stvoreno_u_radnom_odnosu" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="Nacin_koriscenja_dela" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "naslovDela",
        "alternativniNaslov",
        "deloPrerade",
        "vrstaAutorskogDela",
        "formaZapisa",
        "deloStvorenoURadnomOdnosu",
        "nacinKoriscenjaDela"
})
@XmlRootElement(name = "Delo")
public class Delo {

    @XmlElement(name = "Naslov_dela", required = true)
    protected String naslovDela;
    @XmlElement(name = "Alternativni_naslov")
    protected String alternativniNaslov;
    @XmlElement(name = "Delo_prerade")
    protected DeloPrerade deloPrerade;
    @XmlElement(name = "Vrsta_autorskog_dela", required = true)
    protected String vrstaAutorskogDela;
    @XmlElement(name = "Forma_zapisa", required = true)
    protected String formaZapisa;
    @XmlElement(name = "Delo_stvoreno_u_radnom_odnosu")
    protected Boolean deloStvorenoURadnomOdnosu;
    @XmlElement(name = "Nacin_koriscenja_dela")
    protected String nacinKoriscenjaDela;

    /**
     * Gets the value of the naslovDela property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getNaslovDela() {
        return naslovDela;
    }

    /**
     * Sets the value of the naslovDela property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setNaslovDela(String value) {
        this.naslovDela = value;
    }

    /**
     * Gets the value of the alternativniNaslov property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAlternativniNaslov() {
        return alternativniNaslov;
    }

    /**
     * Sets the value of the alternativniNaslov property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAlternativniNaslov(String value) {
        this.alternativniNaslov = value;
    }

    /**
     * Gets the value of the deloPrerade property.
     *
     * @return possible object is
     * {@link DeloPrerade }
     */
    public DeloPrerade getDeloPrerade() {
        return deloPrerade;
    }

    /**
     * Sets the value of the deloPrerade property.
     *
     * @param value allowed object is
     *              {@link DeloPrerade }
     */
    public void setDeloPrerade(DeloPrerade value) {
        this.deloPrerade = value;
    }

    /**
     * Gets the value of the vrstaAutorskogDela property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getVrstaAutorskogDela() {
        return vrstaAutorskogDela;
    }

    /**
     * Sets the value of the vrstaAutorskogDela property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setVrstaAutorskogDela(String value) {
        this.vrstaAutorskogDela = value;
    }

    /**
     * Gets the value of the formaZapisa property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFormaZapisa() {
        return formaZapisa;
    }

    /**
     * Sets the value of the formaZapisa property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFormaZapisa(String value) {
        this.formaZapisa = value;
    }

    /**
     * Gets the value of the deloStvorenoURadnomOdnosu property.
     *
     * @return possible object is
     * {@link Boolean }
     */
    public Boolean isDeloStvorenoURadnomOdnosu() {
        return deloStvorenoURadnomOdnosu;
    }

    /**
     * Sets the value of the deloStvorenoURadnomOdnosu property.
     *
     * @param value allowed object is
     *              {@link Boolean }
     */
    public void setDeloStvorenoURadnomOdnosu(Boolean value) {
        this.deloStvorenoURadnomOdnosu = value;
    }

    /**
     * Gets the value of the nacinKoriscenjaDela property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getNacinKoriscenjaDela() {
        return nacinKoriscenjaDela;
    }

    /**
     * Sets the value of the nacinKoriscenjaDela property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setNacinKoriscenjaDela(String value) {
        this.nacinKoriscenjaDela = value;
    }

}
