//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.10 at 06:18:54 PM UTC 
//


package xml.a1.model;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Naslov_izvornog_dela" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element ref="{a1ns}Autor"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "naslovIzvornogDela",
        "autor"
})
@XmlRootElement(name = "Delo_prerade")
public class DeloPrerade {

    @XmlElement(name = "Naslov_izvornog_dela", required = true)
    protected String naslovIzvornogDela;
    @XmlElement(name = "Autor", required = true)
    protected Autor autor;

    /**
     * Gets the value of the naslovIzvornogDela property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getNaslovIzvornogDela() {
        return naslovIzvornogDela;
    }

    /**
     * Sets the value of the naslovIzvornogDela property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setNaslovIzvornogDela(String value) {
        this.naslovIzvornogDela = value;
    }

    /**
     * Gets the value of the autor property.
     *
     * @return possible object is
     * {@link Autor }
     */
    public Autor getAutor() {
        return autor;
    }

    /**
     * Sets the value of the autor property.
     *
     * @param value allowed object is
     *              {@link Autor }
     */
    public void setAutor(Autor value) {
        this.autor = value;
    }

}
