//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.10 at 06:18:54 PM UTC 
//


package xml.a1.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generatedpackage package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Podnosilac_QNAME = new QName("a1ns", "Podnosilac");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generatedpackage
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Zahtev }
     * 
     */
    public Zahtev createZahtev() {
        return new Zahtev();
    }

    /**
     * Create an instance of {@link Autor }
     * 
     */
    public Autor createAutor() {
        return new Autor();
    }

    /**
     * Create an instance of {@link TFizickoLice }
     * 
     */
    public TFizickoLice createTFizickoLice() {
        return new TFizickoLice();
    }

    /**
     * Create an instance of {@link Punomocnik }
     * 
     */
    public Punomocnik createPunomocnik() {
        return new Punomocnik();
    }

    /**
     * Create an instance of {@link Adresa }
     * 
     */
    public Adresa createAdresa() {
        return new Adresa();
    }

    /**
     * Create an instance of {@link Delo }
     * 
     */
    public Delo createDelo() {
        return new Delo();
    }

    /**
     * Create an instance of {@link DeloPrerade }
     * 
     */
    public DeloPrerade createDeloPrerade() {
        return new DeloPrerade();
    }

    /**
     * Create an instance of {@link PopunjavaZavod }
     * 
     */
    public PopunjavaZavod createPopunjavaZavod() {
        return new PopunjavaZavod();
    }

    /**
     * Create an instance of {@link Ustanova }
     * 
     */
    public Ustanova createUstanova() {
        return new Ustanova();
    }

    /**
     * Create an instance of {@link Kontakt }
     * 
     */
    public Kontakt createKontakt() {
        return new Kontakt();
    }

    /**
     * Create an instance of {@link TPravnoLice }
     * 
     */
    public TPravnoLice createTPravnoLice() {
        return new TPravnoLice();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TLice }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TLice }{@code >}
     */
    @XmlElementDecl(namespace = "a1ns", name = "Podnosilac")
    public JAXBElement<TLice> createPodnosilac(TLice value) {
        return new JAXBElement<TLice>(_Podnosilac_QNAME, TLice.class, null, value);
    }

}
