//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.10 at 06:18:54 PM UTC 
//


package xml.a1.model;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{a1ns}Podnosilac"/&gt;
 *         &lt;element ref="{a1ns}Autor" minOccurs="0"/&gt;
 *         &lt;element ref="{a1ns}Punomocnik" minOccurs="0"/&gt;
 *         &lt;element ref="{a1ns}Delo"/&gt;
 *         &lt;element ref="{a1ns}Popunjava_zavod"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "podnosilac",
        "autor",
        "punomocnik",
        "delo",
        "popunjavaZavod"
})
@XmlRootElement(name = "Zahtev")
public class Zahtev {

    @XmlElement(name = "Podnosilac", required = true)
    protected TLice podnosilac;
    @XmlElement(name = "Autor")
    protected Autor autor;
    @XmlElement(name = "Punomocnik")
    protected Punomocnik punomocnik;
    @XmlElement(name = "Delo", required = true)
    protected Delo delo;
    @XmlElement(name = "Popunjava_zavod", required = true)
    protected PopunjavaZavod popunjavaZavod;

    /**
     * Gets the value of the podnosilac property.
     *
     * @return possible object is
     * {@link TLice }
     */
    public TLice getPodnosilac() {
        return podnosilac;
    }

    /**
     * Sets the value of the podnosilac property.
     *
     * @param value allowed object is
     *              {@link TLice }
     */
    public void setPodnosilac(TLice value) {
        this.podnosilac = value;
    }

    /**
     * Gets the value of the autor property.
     *
     * @return possible object is
     * {@link Autor }
     */
    public Autor getAutor() {
        return autor;
    }

    /**
     * Sets the value of the autor property.
     *
     * @param value allowed object is
     *              {@link Autor }
     */
    public void setAutor(Autor value) {
        this.autor = value;
    }

    /**
     * Gets the value of the punomocnik property.
     *
     * @return possible object is
     * {@link Punomocnik }
     */
    public Punomocnik getPunomocnik() {
        return punomocnik;
    }

    /**
     * Sets the value of the punomocnik property.
     *
     * @param value allowed object is
     *              {@link Punomocnik }
     */
    public void setPunomocnik(Punomocnik value) {
        this.punomocnik = value;
    }

    /**
     * Gets the value of the delo property.
     *
     * @return possible object is
     * {@link Delo }
     */
    public Delo getDelo() {
        return delo;
    }

    /**
     * Sets the value of the delo property.
     *
     * @param value allowed object is
     *              {@link Delo }
     */
    public void setDelo(Delo value) {
        this.delo = value;
    }

    /**
     * Gets the value of the popunjavaZavod property.
     *
     * @return possible object is
     * {@link PopunjavaZavod }
     */
    public PopunjavaZavod getPopunjavaZavod() {
        return popunjavaZavod;
    }

    /**
     * Sets the value of the popunjavaZavod property.
     *
     * @param value allowed object is
     *              {@link PopunjavaZavod }
     */
    public void setPopunjavaZavod(PopunjavaZavod value) {
        this.popunjavaZavod = value;
    }

}
