//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.10 at 09:05:51 PM CET 
//


package xml.p1.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Naziv_pronalaska_na_srpskom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Naziv_pronalaska_na_engleskom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nazivPronalaskaNaSrpskom",
    "nazivPronalaskaNaEngleskom"
})
@XmlRootElement(name = "Naziv_pronalaska")
public class NazivPronalaska {

    @XmlElement(name = "Naziv_pronalaska_na_srpskom", required = true)
    protected String nazivPronalaskaNaSrpskom;
    @XmlElement(name = "Naziv_pronalaska_na_engleskom", required = true)
    protected String nazivPronalaskaNaEngleskom;

    /**
     * Gets the value of the nazivPronalaskaNaSrpskom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazivPronalaskaNaSrpskom() {
        return nazivPronalaskaNaSrpskom;
    }

    /**
     * Sets the value of the nazivPronalaskaNaSrpskom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazivPronalaskaNaSrpskom(String value) {
        this.nazivPronalaskaNaSrpskom = value;
    }

    /**
     * Gets the value of the nazivPronalaskaNaEngleskom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazivPronalaskaNaEngleskom() {
        return nazivPronalaskaNaEngleskom;
    }

    /**
     * Sets the value of the nazivPronalaskaNaEngleskom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazivPronalaskaNaEngleskom(String value) {
        this.nazivPronalaskaNaEngleskom = value;
    }

}
