//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.10 at 09:05:51 PM CET 
//


package xml.p1.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PodaciOLicu_QNAME = new QName("p1ns", "Podaci_o_licu");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Kontakt }
     * 
     */
    public Kontakt createKontakt() {
        return new Kontakt();
    }

    /**
     * Create an instance of {@link PopunjavaZavod }
     * 
     */
    public PopunjavaZavod createPopunjavaZavod() {
        return new PopunjavaZavod();
    }

    /**
     * Create an instance of {@link PodnosilacPrijave }
     * 
     */
    public PodnosilacPrijave createPodnosilacPrijave() {
        return new PodnosilacPrijave();
    }

    /**
     * Create an instance of {@link Adresa }
     * 
     */
    public Adresa createAdresa() {
        return new Adresa();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjePatenta }
     * 
     */
    public ZahtevZaPriznanjePatenta createZahtevZaPriznanjePatenta() {
        return new ZahtevZaPriznanjePatenta();
    }

    /**
     * Create an instance of {@link NazivPronalaska }
     * 
     */
    public NazivPronalaska createNazivPronalaska() {
        return new NazivPronalaska();
    }

    /**
     * Create an instance of {@link PronalazacPatenta }
     * 
     */
    public PronalazacPatenta createPronalazacPatenta() {
        return new PronalazacPatenta();
    }

    /**
     * Create an instance of {@link PredstavnikPatenta }
     * 
     */
    public PredstavnikPatenta createPredstavnikPatenta() {
        return new PredstavnikPatenta();
    }

    /**
     * Create an instance of {@link Dostavljanje }
     * 
     */
    public Dostavljanje createDostavljanje() {
        return new Dostavljanje();
    }

    /**
     * Create an instance of {@link ZahteviZaPriznanjePravaPrvenstvaIzRanijihPrijava }
     * 
     */
    public ZahteviZaPriznanjePravaPrvenstvaIzRanijihPrijava createZahteviZaPriznanjePravaPrvenstvaIzRanijihPrijava() {
        return new ZahteviZaPriznanjePravaPrvenstvaIzRanijihPrijava();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjePravaPrvenstvaIzRanijihPrijava }
     * 
     */
    public ZahtevZaPriznanjePravaPrvenstvaIzRanijihPrijava createZahtevZaPriznanjePravaPrvenstvaIzRanijihPrijava() {
        return new ZahtevZaPriznanjePravaPrvenstvaIzRanijihPrijava();
    }

    /**
     * Create an instance of {@link TPravnoLice }
     * 
     */
    public TPravnoLice createTPravnoLice() {
        return new TPravnoLice();
    }

    /**
     * Create an instance of {@link TFizickoLice }
     * 
     */
    public TFizickoLice createTFizickoLice() {
        return new TFizickoLice();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TLice }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "p1ns", name = "Podaci_o_licu")
    public JAXBElement<TLice> createPodaciOLicu(TLice value) {
        return new JAXBElement<TLice>(_PodaciOLicu_QNAME, TLice.class, null, value);
    }

}
