//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.10 at 09:05:51 PM CET 
//


package xml.p1.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{p1ns}Podaci_o_licu"/>
 *         &lt;element name="Punomocnik">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="zastupanje"/>
 *               &lt;enumeration value="prijem_pismena"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Zajednicki_predstavnik" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "podaciOLicu",
    "punomocnik",
    "zajednickiPredstavnik"
})
@XmlRootElement(name = "Predstavnik_patenta")
public class PredstavnikPatenta {

    @XmlElement(name = "Podaci_o_licu", required = true)
    protected TLice podaciOLicu;
    @XmlElement(name = "Punomocnik", required = true, nillable = true)
    protected String punomocnik;
    @XmlElement(name = "Zajednicki_predstavnik")
    protected boolean zajednickiPredstavnik;

    /**
     * Gets the value of the podaciOLicu property.
     * 
     * @return
     *     possible object is
     *     {@link TLice }
     *     
     */
    public TLice getPodaciOLicu() {
        return podaciOLicu;
    }

    /**
     * Sets the value of the podaciOLicu property.
     * 
     * @param value
     *     allowed object is
     *     {@link TLice }
     *     
     */
    public void setPodaciOLicu(TLice value) {
        this.podaciOLicu = value;
    }

    /**
     * Gets the value of the punomocnik property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPunomocnik() {
        return punomocnik;
    }

    /**
     * Sets the value of the punomocnik property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPunomocnik(String value) {
        this.punomocnik = value;
    }

    /**
     * Gets the value of the zajednickiPredstavnik property.
     * 
     */
    public boolean isZajednickiPredstavnik() {
        return zajednickiPredstavnik;
    }

    /**
     * Sets the value of the zajednickiPredstavnik property.
     * 
     */
    public void setZajednickiPredstavnik(boolean value) {
        this.zajednickiPredstavnik = value;
    }

}
