//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.10 at 09:05:51 PM CET 
//


package xml.p1.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Datum_podnosenja_ranije_prijave" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="Broj_ranije_prijave" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Dvoslovna_oznaka_drzave_regionalne_ili_medjunarodne_organizacije" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "datumPodnosenjaRanijePrijave",
    "brojRanijePrijave",
    "dvoslovnaOznakaDrzaveRegionalneIliMedjunarodneOrganizacije"
})
@XmlRootElement(name = "Zahtev_za_priznanje_prava_prvenstva_iz_ranijih_prijava")
public class ZahtevZaPriznanjePravaPrvenstvaIzRanijihPrijava {

    @XmlElement(name = "Datum_podnosenja_ranije_prijave", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumPodnosenjaRanijePrijave;
    @XmlElement(name = "Broj_ranije_prijave", required = true)
    protected String brojRanijePrijave;
    @XmlElement(name = "Dvoslovna_oznaka_drzave_regionalne_ili_medjunarodne_organizacije", required = true)
    protected String dvoslovnaOznakaDrzaveRegionalneIliMedjunarodneOrganizacije;

    /**
     * Gets the value of the datumPodnosenjaRanijePrijave property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumPodnosenjaRanijePrijave() {
        return datumPodnosenjaRanijePrijave;
    }

    /**
     * Sets the value of the datumPodnosenjaRanijePrijave property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumPodnosenjaRanijePrijave(XMLGregorianCalendar value) {
        this.datumPodnosenjaRanijePrijave = value;
    }

    /**
     * Gets the value of the brojRanijePrijave property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrojRanijePrijave() {
        return brojRanijePrijave;
    }

    /**
     * Sets the value of the brojRanijePrijave property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrojRanijePrijave(String value) {
        this.brojRanijePrijave = value;
    }

    /**
     * Gets the value of the dvoslovnaOznakaDrzaveRegionalneIliMedjunarodneOrganizacije property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDvoslovnaOznakaDrzaveRegionalneIliMedjunarodneOrganizacije() {
        return dvoslovnaOznakaDrzaveRegionalneIliMedjunarodneOrganizacije;
    }

    /**
     * Sets the value of the dvoslovnaOznakaDrzaveRegionalneIliMedjunarodneOrganizacije property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDvoslovnaOznakaDrzaveRegionalneIliMedjunarodneOrganizacije(String value) {
        this.dvoslovnaOznakaDrzaveRegionalneIliMedjunarodneOrganizacije = value;
    }

}
