//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.10 at 09:05:51 PM CET 
//


package xml.p1.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{p1ns}Popunjava_zavod"/>
 *         &lt;element ref="{p1ns}Naziv_pronalaska"/>
 *         &lt;element ref="{p1ns}Podnosilac_prijave"/>
 *         &lt;element ref="{p1ns}Pronalazac_patenta" minOccurs="0"/>
 *         &lt;element ref="{p1ns}Predstavnik_patenta"/>
 *         &lt;element ref="{p1ns}Dostavljanje"/>
 *         &lt;element ref="{p1ns}Zahtevi_za_priznanje_prava_prvenstva_iz_ranijih_prijava"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "popunjavaZavod",
    "nazivPronalaska",
    "podnosilacPrijave",
    "pronalazacPatenta",
    "predstavnikPatenta",
    "dostavljanje",
    "zahteviZaPriznanjePravaPrvenstvaIzRanijihPrijava"
})
@XmlRootElement(name = "Zahtev_za_priznanje_patenta")
public class ZahtevZaPriznanjePatenta {

    @XmlElement(name = "Popunjava_zavod", required = true)
    protected PopunjavaZavod popunjavaZavod;
    @XmlElement(name = "Naziv_pronalaska", required = true)
    protected NazivPronalaska nazivPronalaska;
    @XmlElement(name = "Podnosilac_prijave", required = true)
    protected PodnosilacPrijave podnosilacPrijave;
    @XmlElement(name = "Pronalazac_patenta")
    protected PronalazacPatenta pronalazacPatenta;
    @XmlElement(name = "Predstavnik_patenta", required = true)
    protected PredstavnikPatenta predstavnikPatenta;
    @XmlElement(name = "Dostavljanje", required = true)
    protected Dostavljanje dostavljanje;
    @XmlElement(name = "Zahtevi_za_priznanje_prava_prvenstva_iz_ranijih_prijava", required = true)
    protected ZahteviZaPriznanjePravaPrvenstvaIzRanijihPrijava zahteviZaPriznanjePravaPrvenstvaIzRanijihPrijava;

    /**
     * Gets the value of the popunjavaZavod property.
     * 
     * @return
     *     possible object is
     *     {@link PopunjavaZavod }
     *     
     */
    public PopunjavaZavod getPopunjavaZavod() {
        return popunjavaZavod;
    }

    /**
     * Sets the value of the popunjavaZavod property.
     * 
     * @param value
     *     allowed object is
     *     {@link PopunjavaZavod }
     *     
     */
    public void setPopunjavaZavod(PopunjavaZavod value) {
        this.popunjavaZavod = value;
    }

    /**
     * Gets the value of the nazivPronalaska property.
     * 
     * @return
     *     possible object is
     *     {@link NazivPronalaska }
     *     
     */
    public NazivPronalaska getNazivPronalaska() {
        return nazivPronalaska;
    }

    /**
     * Sets the value of the nazivPronalaska property.
     * 
     * @param value
     *     allowed object is
     *     {@link NazivPronalaska }
     *     
     */
    public void setNazivPronalaska(NazivPronalaska value) {
        this.nazivPronalaska = value;
    }

    /**
     * Gets the value of the podnosilacPrijave property.
     * 
     * @return
     *     possible object is
     *     {@link PodnosilacPrijave }
     *     
     */
    public PodnosilacPrijave getPodnosilacPrijave() {
        return podnosilacPrijave;
    }

    /**
     * Sets the value of the podnosilacPrijave property.
     * 
     * @param value
     *     allowed object is
     *     {@link PodnosilacPrijave }
     *     
     */
    public void setPodnosilacPrijave(PodnosilacPrijave value) {
        this.podnosilacPrijave = value;
    }

    /**
     * Gets the value of the pronalazacPatenta property.
     * 
     * @return
     *     possible object is
     *     {@link PronalazacPatenta }
     *     
     */
    public PronalazacPatenta getPronalazacPatenta() {
        return pronalazacPatenta;
    }

    /**
     * Sets the value of the pronalazacPatenta property.
     * 
     * @param value
     *     allowed object is
     *     {@link PronalazacPatenta }
     *     
     */
    public void setPronalazacPatenta(PronalazacPatenta value) {
        this.pronalazacPatenta = value;
    }

    /**
     * Gets the value of the predstavnikPatenta property.
     * 
     * @return
     *     possible object is
     *     {@link PredstavnikPatenta }
     *     
     */
    public PredstavnikPatenta getPredstavnikPatenta() {
        return predstavnikPatenta;
    }

    /**
     * Sets the value of the predstavnikPatenta property.
     * 
     * @param value
     *     allowed object is
     *     {@link PredstavnikPatenta }
     *     
     */
    public void setPredstavnikPatenta(PredstavnikPatenta value) {
        this.predstavnikPatenta = value;
    }

    /**
     * Gets the value of the dostavljanje property.
     * 
     * @return
     *     possible object is
     *     {@link Dostavljanje }
     *     
     */
    public Dostavljanje getDostavljanje() {
        return dostavljanje;
    }

    /**
     * Sets the value of the dostavljanje property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dostavljanje }
     *     
     */
    public void setDostavljanje(Dostavljanje value) {
        this.dostavljanje = value;
    }

    /**
     * Gets the value of the zahteviZaPriznanjePravaPrvenstvaIzRanijihPrijava property.
     * 
     * @return
     *     possible object is
     *     {@link ZahteviZaPriznanjePravaPrvenstvaIzRanijihPrijava }
     *     
     */
    public ZahteviZaPriznanjePravaPrvenstvaIzRanijihPrijava getZahteviZaPriznanjePravaPrvenstvaIzRanijihPrijava() {
        return zahteviZaPriznanjePravaPrvenstvaIzRanijihPrijava;
    }

    /**
     * Sets the value of the zahteviZaPriznanjePravaPrvenstvaIzRanijihPrijava property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZahteviZaPriznanjePravaPrvenstvaIzRanijihPrijava }
     *     
     */
    public void setZahteviZaPriznanjePravaPrvenstvaIzRanijihPrijava(ZahteviZaPriznanjePravaPrvenstvaIzRanijihPrijava value) {
        this.zahteviZaPriznanjePravaPrvenstvaIzRanijihPrijava = value;
    }

}
