//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.10 at 10:07:27 PM CET 
//


package xml.z1.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PodaciOZajednickomPredstavniku_QNAME = new QName("http://www.ftn.uns.ac.rs/z1", "Podaci_o_zajednickom_predstavniku");
    private final static QName _PodaciOPunomocniku_QNAME = new QName("http://www.ftn.uns.ac.rs/z1", "Podaci_o_punomocniku");
    private final static QName _PodaciOPodnosiocuPrijave_QNAME = new QName("http://www.ftn.uns.ac.rs/z1", "Podaci_o_podnosiocu_prijave");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Kontakt }
     * 
     */
    public Kontakt createKontakt() {
        return new Kontakt();
    }

    /**
     * Create an instance of {@link ZahtevZaPriznanjeZiga }
     * 
     */
    public ZahtevZaPriznanjeZiga createZahtevZaPriznanjeZiga() {
        return new ZahtevZaPriznanjeZiga();
    }

    /**
     * Create an instance of {@link PrijavaSePodnosiZa }
     * 
     */
    public PrijavaSePodnosiZa createPrijavaSePodnosiZa() {
        return new PrijavaSePodnosiZa();
    }

    /**
     * Create an instance of {@link TaksePlaceneUDinarima }
     * 
     */
    public TaksePlaceneUDinarima createTaksePlaceneUDinarima() {
        return new TaksePlaceneUDinarima();
    }

    /**
     * Create an instance of {@link PopunjavaZavod }
     * 
     */
    public PopunjavaZavod createPopunjavaZavod() {
        return new PopunjavaZavod();
    }

    /**
     * Create an instance of {@link PrikloziUzZahtev }
     * 
     */
    public PrikloziUzZahtev createPrikloziUzZahtev() {
        return new PrikloziUzZahtev();
    }

    /**
     * Create an instance of {@link Adresa }
     * 
     */
    public Adresa createAdresa() {
        return new Adresa();
    }

    /**
     * Create an instance of {@link PopunjavaPodnosioc }
     * 
     */
    public PopunjavaPodnosioc createPopunjavaPodnosioc() {
        return new PopunjavaPodnosioc();
    }

    /**
     * Create an instance of {@link TFizickoLice }
     * 
     */
    public TFizickoLice createTFizickoLice() {
        return new TFizickoLice();
    }

    /**
     * Create an instance of {@link TPravnoLice }
     * 
     */
    public TPravnoLice createTPravnoLice() {
        return new TPravnoLice();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TLice }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/z1", name = "Podaci_o_zajednickom_predstavniku")
    public JAXBElement<TLice> createPodaciOZajednickomPredstavniku(TLice value) {
        return new JAXBElement<TLice>(_PodaciOZajednickomPredstavniku_QNAME, TLice.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TLice }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/z1", name = "Podaci_o_punomocniku")
    public JAXBElement<TLice> createPodaciOPunomocniku(TLice value) {
        return new JAXBElement<TLice>(_PodaciOPunomocniku_QNAME, TLice.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TLice }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/z1", name = "Podaci_o_podnosiocu_prijave")
    public JAXBElement<TLice> createPodaciOPodnosiocuPrijave(TLice value) {
        return new JAXBElement<TLice>(_PodaciOPodnosiocuPrijave_QNAME, TLice.class, null, value);
    }

}
