//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.10 at 10:07:27 PM CET 
//


package xml.z1.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/z1}Priklozi_uz_zahtev"/>
 *         &lt;element name="Broj_prijave_ziga" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Datum_podnosenja" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "prikloziUzZahtev",
    "brojPrijaveZiga",
    "datumPodnosenja"
})
@XmlRootElement(name = "Popunjava_zavod")
public class PopunjavaZavod {

    @XmlElement(name = "Priklozi_uz_zahtev", required = true)
    protected PrikloziUzZahtev prikloziUzZahtev;
    @XmlElement(name = "Broj_prijave_ziga", required = true)
    protected String brojPrijaveZiga;
    @XmlElement(name = "Datum_podnosenja", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumPodnosenja;

    /**
     * Gets the value of the prikloziUzZahtev property.
     * 
     * @return
     *     possible object is
     *     {@link PrikloziUzZahtev }
     *     
     */
    public PrikloziUzZahtev getPrikloziUzZahtev() {
        return prikloziUzZahtev;
    }

    /**
     * Sets the value of the prikloziUzZahtev property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrikloziUzZahtev }
     *     
     */
    public void setPrikloziUzZahtev(PrikloziUzZahtev value) {
        this.prikloziUzZahtev = value;
    }

    /**
     * Gets the value of the brojPrijaveZiga property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrojPrijaveZiga() {
        return brojPrijaveZiga;
    }

    /**
     * Sets the value of the brojPrijaveZiga property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrojPrijaveZiga(String value) {
        this.brojPrijaveZiga = value;
    }

    /**
     * Gets the value of the datumPodnosenja property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumPodnosenja() {
        return datumPodnosenja;
    }

    /**
     * Sets the value of the datumPodnosenja property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumPodnosenja(XMLGregorianCalendar value) {
        this.datumPodnosenja = value;
    }

}
