//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.10 at 10:07:27 PM CET 
//


package xml.z1.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Podaci_o_podnosiocu_prijave" type="{http://www.ftn.uns.ac.rs/z1}TFizicko_lice"/>
 *         &lt;element name="Podaci_o_punomocniku" type="{http://www.ftn.uns.ac.rs/z1}TFizicko_lice"/>
 *         &lt;element name="Podaci_o_zajednickom_predstavniku" type="{http://www.ftn.uns.ac.rs/z1}TFizicko_lice"/>
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/z1}Prijava_se_podnosi_za"/>
 *         &lt;element name="Naznacenje_boje" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Transliteracija_znaka" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Prevod_znaka" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Opis_znaka" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Nicanska_klasifikacija">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}positiveInteger">
 *               &lt;maxInclusive value="45"/>
 *               &lt;minInclusive value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Zatrazeno_pravo_prvenstva_i_osnov" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/z1}Takse_placene_u_dinarima"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "podaciOPodnosiocuPrijave",
    "podaciOPunomocniku",
    "podaciOZajednickomPredstavniku",
    "prijavaSePodnosiZa",
    "naznacenjeBoje",
    "transliteracijaZnaka",
    "prevodZnaka",
    "opisZnaka",
    "nicanskaKlasifikacija",
    "zatrazenoPravoPrvenstvaIOsnov",
    "taksePlaceneUDinarima"
})
@XmlRootElement(name = "Popunjava_podnosioc")
public class PopunjavaPodnosioc {

    @XmlElement(name = "Podaci_o_podnosiocu_prijave", required = true)
    protected TFizickoLice podaciOPodnosiocuPrijave;
    @XmlElement(name = "Podaci_o_punomocniku", required = true)
    protected TFizickoLice podaciOPunomocniku;
    @XmlElement(name = "Podaci_o_zajednickom_predstavniku", required = true)
    protected TFizickoLice podaciOZajednickomPredstavniku;
    @XmlElement(name = "Prijava_se_podnosi_za", required = true)
    protected PrijavaSePodnosiZa prijavaSePodnosiZa;
    @XmlElement(name = "Naznacenje_boje", required = true)
    protected String naznacenjeBoje;
    @XmlElement(name = "Transliteracija_znaka")
    protected String transliteracijaZnaka;
    @XmlElement(name = "Prevod_znaka")
    protected String prevodZnaka;
    @XmlElement(name = "Opis_znaka", required = true)
    protected String opisZnaka;
    @XmlElement(name = "Nicanska_klasifikacija")
    protected int nicanskaKlasifikacija;
    @XmlElement(name = "Zatrazeno_pravo_prvenstva_i_osnov", required = true)
    protected String zatrazenoPravoPrvenstvaIOsnov;
    @XmlElement(name = "Takse_placene_u_dinarima", required = true)
    protected TaksePlaceneUDinarima taksePlaceneUDinarima;

    /**
     * Gets the value of the podaciOPodnosiocuPrijave property.
     * 
     * @return
     *     possible object is
     *     {@link TFizickoLice }
     *     
     */
    public TFizickoLice getPodaciOPodnosiocuPrijave() {
        return podaciOPodnosiocuPrijave;
    }

    /**
     * Sets the value of the podaciOPodnosiocuPrijave property.
     * 
     * @param value
     *     allowed object is
     *     {@link TFizickoLice }
     *     
     */
    public void setPodaciOPodnosiocuPrijave(TFizickoLice value) {
        this.podaciOPodnosiocuPrijave = value;
    }

    /**
     * Gets the value of the podaciOPunomocniku property.
     * 
     * @return
     *     possible object is
     *     {@link TFizickoLice }
     *     
     */
    public TFizickoLice getPodaciOPunomocniku() {
        return podaciOPunomocniku;
    }

    /**
     * Sets the value of the podaciOPunomocniku property.
     * 
     * @param value
     *     allowed object is
     *     {@link TFizickoLice }
     *     
     */
    public void setPodaciOPunomocniku(TFizickoLice value) {
        this.podaciOPunomocniku = value;
    }

    /**
     * Gets the value of the podaciOZajednickomPredstavniku property.
     * 
     * @return
     *     possible object is
     *     {@link TFizickoLice }
     *     
     */
    public TFizickoLice getPodaciOZajednickomPredstavniku() {
        return podaciOZajednickomPredstavniku;
    }

    /**
     * Sets the value of the podaciOZajednickomPredstavniku property.
     * 
     * @param value
     *     allowed object is
     *     {@link TFizickoLice }
     *     
     */
    public void setPodaciOZajednickomPredstavniku(TFizickoLice value) {
        this.podaciOZajednickomPredstavniku = value;
    }

    /**
     * Gets the value of the prijavaSePodnosiZa property.
     * 
     * @return
     *     possible object is
     *     {@link PrijavaSePodnosiZa }
     *     
     */
    public PrijavaSePodnosiZa getPrijavaSePodnosiZa() {
        return prijavaSePodnosiZa;
    }

    /**
     * Sets the value of the prijavaSePodnosiZa property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrijavaSePodnosiZa }
     *     
     */
    public void setPrijavaSePodnosiZa(PrijavaSePodnosiZa value) {
        this.prijavaSePodnosiZa = value;
    }

    /**
     * Gets the value of the naznacenjeBoje property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNaznacenjeBoje() {
        return naznacenjeBoje;
    }

    /**
     * Sets the value of the naznacenjeBoje property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNaznacenjeBoje(String value) {
        this.naznacenjeBoje = value;
    }

    /**
     * Gets the value of the transliteracijaZnaka property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransliteracijaZnaka() {
        return transliteracijaZnaka;
    }

    /**
     * Sets the value of the transliteracijaZnaka property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransliteracijaZnaka(String value) {
        this.transliteracijaZnaka = value;
    }

    /**
     * Gets the value of the prevodZnaka property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrevodZnaka() {
        return prevodZnaka;
    }

    /**
     * Sets the value of the prevodZnaka property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrevodZnaka(String value) {
        this.prevodZnaka = value;
    }

    /**
     * Gets the value of the opisZnaka property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpisZnaka() {
        return opisZnaka;
    }

    /**
     * Sets the value of the opisZnaka property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpisZnaka(String value) {
        this.opisZnaka = value;
    }

    /**
     * Gets the value of the nicanskaKlasifikacija property.
     * 
     */
    public int getNicanskaKlasifikacija() {
        return nicanskaKlasifikacija;
    }

    /**
     * Sets the value of the nicanskaKlasifikacija property.
     * 
     */
    public void setNicanskaKlasifikacija(int value) {
        this.nicanskaKlasifikacija = value;
    }

    /**
     * Gets the value of the zatrazenoPravoPrvenstvaIOsnov property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZatrazenoPravoPrvenstvaIOsnov() {
        return zatrazenoPravoPrvenstvaIOsnov;
    }

    /**
     * Sets the value of the zatrazenoPravoPrvenstvaIOsnov property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZatrazenoPravoPrvenstvaIOsnov(String value) {
        this.zatrazenoPravoPrvenstvaIOsnov = value;
    }

    /**
     * Gets the value of the taksePlaceneUDinarima property.
     * 
     * @return
     *     possible object is
     *     {@link TaksePlaceneUDinarima }
     *     
     */
    public TaksePlaceneUDinarima getTaksePlaceneUDinarima() {
        return taksePlaceneUDinarima;
    }

    /**
     * Sets the value of the taksePlaceneUDinarima property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaksePlaceneUDinarima }
     *     
     */
    public void setTaksePlaceneUDinarima(TaksePlaceneUDinarima value) {
        this.taksePlaceneUDinarima = value;
    }

}
