//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.10 at 10:07:27 PM CET 
//


package xml.z1.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Vrsta_ziga">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Individualni zig"/>
 *               &lt;enumeration value="Kolektivni zig"/>
 *               &lt;enumeration value="Zig garancije"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Vrsta_znaka">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Verbalni znak"/>
 *               &lt;enumeration value="Graficki znak"/>
 *               &lt;enumeration value="Kombinovani znak"/>
 *               &lt;whiteSpace value="preserve"/>
 *               &lt;enumeration value="Trodimenzionalni znak"/>
 *               &lt;enumeration value="Druga vrsta znaka"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Izgled_znaka" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "vrstaZiga",
    "vrstaZnaka",
    "izgledZnaka"
})
@XmlRootElement(name = "Prijava_se_podnosi_za")
public class PrijavaSePodnosiZa {

    @XmlElement(name = "Vrsta_ziga", required = true)
    protected String vrstaZiga;
    @XmlElement(name = "Vrsta_znaka", required = true)
    protected String vrstaZnaka;
    @XmlElement(name = "Izgled_znaka", required = true)
    protected Object izgledZnaka;

    /**
     * Gets the value of the vrstaZiga property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVrstaZiga() {
        return vrstaZiga;
    }

    /**
     * Sets the value of the vrstaZiga property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVrstaZiga(String value) {
        this.vrstaZiga = value;
    }

    /**
     * Gets the value of the vrstaZnaka property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVrstaZnaka() {
        return vrstaZnaka;
    }

    /**
     * Sets the value of the vrstaZnaka property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVrstaZnaka(String value) {
        this.vrstaZnaka = value;
    }

    /**
     * Gets the value of the izgledZnaka property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getIzgledZnaka() {
        return izgledZnaka;
    }

    /**
     * Sets the value of the izgledZnaka property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setIzgledZnaka(Object value) {
        this.izgledZnaka = value;
    }

}
