//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.10 at 10:07:27 PM CET 
//


package xml.z1.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Osnovna_taksa" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="Za_odredjenu_klasu" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="Za_graficko_resenje" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="Ukupno" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "osnovnaTaksa",
    "zaOdredjenuKlasu",
    "zaGrafickoResenje",
    "ukupno"
})
@XmlRootElement(name = "Takse_placene_u_dinarima")
public class TaksePlaceneUDinarima {

    @XmlElement(name = "Osnovna_taksa", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger osnovnaTaksa;
    @XmlElement(name = "Za_odredjenu_klasu", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger zaOdredjenuKlasu;
    @XmlElement(name = "Za_graficko_resenje", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger zaGrafickoResenje;
    @XmlElement(name = "Ukupno", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger ukupno;

    /**
     * Gets the value of the osnovnaTaksa property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOsnovnaTaksa() {
        return osnovnaTaksa;
    }

    /**
     * Sets the value of the osnovnaTaksa property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOsnovnaTaksa(BigInteger value) {
        this.osnovnaTaksa = value;
    }

    /**
     * Gets the value of the zaOdredjenuKlasu property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getZaOdredjenuKlasu() {
        return zaOdredjenuKlasu;
    }

    /**
     * Sets the value of the zaOdredjenuKlasu property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setZaOdredjenuKlasu(BigInteger value) {
        this.zaOdredjenuKlasu = value;
    }

    /**
     * Gets the value of the zaGrafickoResenje property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getZaGrafickoResenje() {
        return zaGrafickoResenje;
    }

    /**
     * Sets the value of the zaGrafickoResenje property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setZaGrafickoResenje(BigInteger value) {
        this.zaGrafickoResenje = value;
    }

    /**
     * Gets the value of the ukupno property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getUkupno() {
        return ukupno;
    }

    /**
     * Sets the value of the ukupno property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setUkupno(BigInteger value) {
        this.ukupno = value;
    }

}
